GatewayEnabled = true
# Set the max number of open files (see: ulimit -n)
UlimitNOFile = 8192

[API]
  Level = "Debug"
  Timeout = "5s"
  Port = 3007
  IP = "0.0.0.0"
  StreamRetries = 3
  CoreNodeIP = "localhost"
  CoreNodeGRPCPort = 3002

[Accounts]
  Level = "Debug"

[Candles]
  Level = "Debug"

[Logging]
  Environment = "dev"
  # This section takes effect only when Environment is set to "custom".
  [Logging.Custom]
    [Logging.Custom.Zap]
      Level = -1
      Development = true
      Encoding = "console"
      OutputPaths = ["stdout"]
      ErrorOutputPaths = ["stderr"]
    [Logging.Custom.ZapEncoder]
      CallerKey = "C"
      EncodeCaller = "short"
      EncodeDuration = "string"
      EncodeLevel = "capital"
      EncodeName = "full"
      EncodeTime = "iso8601"
      LevelKey = "L"
      LineEnding = "\n"
      MessageKey = "M"
      NameKey = "N"
      TimeKey = "T"

[Markets]
  Level = "Debug"

[Oracles]
  Level = "Debug"

[Orders]
  Level = "Debug"

[Liquidity]
  Level = "Debug"

[Parties]
  Level = "Debug"

[Risk]
  Level = "Debug"

[Storage]
  Level = "Warning"
  Timeout = "5s"
  LogPositionStoreDebug = false
  [Storage.Accounts]
    SyncWrites = true
    TableLoadingMode = "MemoryMap"
    ValueLogLoadingMode = "MemoryMap"
    NumVersionsToKeep = 1
    MaxTableSize = 67108864
    LevelSizeMultiplier = 2
    MaxLevels = 10
    ValueThreshold = 16
    NumMemtables = 1
    NumLevelZeroTables = 1
    NumLevelZeroTablesStall = 2
    LevelOneSize = 268435456
    ValueLogFileSize = 1073741823
    ValueLogMaxEntries = 2500000
    NumCompactors = 2
    CompactL0OnClose = true
    ReadOnly = false
    Truncate = false
    LogRotatesToFlush = 2
    Compression = 1
    EventLogging = true
    BlockSize = 4096
    BloomFalsePositive = 0.01
    KeepL0InMemory = false
    MaxCacheSize = 16777216
    VerifyValueChecksum = false
    ChecksumVerificationMode = 0
  [Storage.Candles]
    SyncWrites = true
    TableLoadingMode = "MemoryMap"
    ValueLogLoadingMode = "MemoryMap"
    NumVersionsToKeep = 1
    MaxTableSize = 67108864
    LevelSizeMultiplier = 2
    MaxLevels = 10
    ValueThreshold = 16
    NumMemtables = 1
    NumLevelZeroTables = 1
    NumLevelZeroTablesStall = 2
    LevelOneSize = 268435456
    ValueLogFileSize = 1073741823
    ValueLogMaxEntries = 2500000
    NumCompactors = 2
    CompactL0OnClose = true
    ReadOnly = false
    Truncate = false
    LogRotatesToFlush = 2
    Compression = 1
    EventLogging = true
    BlockSize = 4096
    BloomFalsePositive = 0.01
    KeepL0InMemory = false
    MaxCacheSize = 16777216
    VerifyValueChecksum = false
    ChecksumVerificationMode = 0
  [Storage.Checkpoints]
    SyncWrites = true
    TableLoadingMode = "MemoryMap"
    ValueLogLoadingMode = "MemoryMap"
    NumVersionsToKeep = 1
    MaxTableSize = 67108864
    LevelSizeMultiplier = 2
    MaxLevels = 10
    ValueThreshold = 16
    NumMemtables = 1
    NumLevelZeroTables = 1
    NumLevelZeroTablesStall = 2
    LevelOneSize = 268435456
    ValueLogFileSize = 1073741823
    ValueLogMaxEntries = 2500000
    NumCompactors = 2
    CompactL0OnClose = true
    ReadOnly = false
    Truncate = false
    LogRotatesToFlush = 2
    Compression = 1
    EventLogging = true
    BlockSize = 4096
    BloomFalsePositive = 0.01
    KeepL0InMemory = false
    MaxCacheSize = 16777216
    VerifyValueChecksum = false
    ChecksumVerificationMode = 0
  [Storage.Markets]
    SyncWrites = true
    TableLoadingMode = "MemoryMap"
    ValueLogLoadingMode = "MemoryMap"
    NumVersionsToKeep = 1
    MaxTableSize = 67108864
    LevelSizeMultiplier = 2
    MaxLevels = 10
    ValueThreshold = 16
    NumMemtables = 1
    NumLevelZeroTables = 1
    NumLevelZeroTablesStall = 2
    LevelOneSize = 268435456
    ValueLogFileSize = 1073741823
    ValueLogMaxEntries = 2500000
    NumCompactors = 2
    CompactL0OnClose = true
    ReadOnly = false
    Truncate = false
    LogRotatesToFlush = 2
    Compression = 1
    EventLogging = true
    BlockSize = 4096
    BloomFalsePositive = 0.01
    KeepL0InMemory = false
    MaxCacheSize = 16777216
    VerifyValueChecksum = false
    ChecksumVerificationMode = 0
  [Storage.Orders]
    SyncWrites = true
    TableLoadingMode = "MemoryMap"
    ValueLogLoadingMode = "MemoryMap"
    NumVersionsToKeep = 1
    MaxTableSize = 67108864
    LevelSizeMultiplier = 2
    MaxLevels = 10
    ValueThreshold = 16
    NumMemtables = 1
    NumLevelZeroTables = 1
    NumLevelZeroTablesStall = 2
    LevelOneSize = 268435456
    ValueLogFileSize = 1073741823
    ValueLogMaxEntries = 2500000
    NumCompactors = 2
    CompactL0OnClose = true
    ReadOnly = false
    Truncate = false
    LogRotatesToFlush = 2
    Compression = 1
    EventLogging = true
    BlockSize = 4096
    BloomFalsePositive = 0.01
    KeepL0InMemory = false
    MaxCacheSize = 16777216
    VerifyValueChecksum = false
    ChecksumVerificationMode = 0
  [Storage.Trades]
    SyncWrites = true
    TableLoadingMode = "MemoryMap"
    ValueLogLoadingMode = "MemoryMap"
    NumVersionsToKeep = 1
    MaxTableSize = 67108864
    LevelSizeMultiplier = 2
    MaxLevels = 10
    ValueThreshold = 16
    NumMemtables = 1
    NumLevelZeroTables = 1
    NumLevelZeroTablesStall = 2
    LevelOneSize = 268435456
    ValueLogFileSize = 1073741823
    ValueLogMaxEntries = 2500000
    NumCompactors = 2
    CompactL0OnClose = true
    ReadOnly = false
    Truncate = false
    LogRotatesToFlush = 2
    Compression = 1
    EventLogging = true
    BlockSize = 4096
    BloomFalsePositive = 0.01
    KeepL0InMemory = false
    MaxCacheSize = 16777216
    VerifyValueChecksum = false
    ChecksumVerificationMode = 0

[Trades]
  Level = "Debug"
  PageSizeDefault = 200
  PageSizeMaximum = 200

[Time]
  Level = "Debug"

[Gateway]
  Level = "Debug"
  Timeout = "5s"
  SubscriptionRetries = 3
  GraphQLPlaygroundEnabled = true
  [Gateway.Node]
    Port = 3007
    IP = "0.0.0.0"
  [Gateway.GraphQL]
    Port = 3008
    IP = "0.0.0.0"
    Enabled = true
    ComplexityLimit = 0
  [Gateway.REST]
    Port = 3009
    IP = "0.0.0.0"
    Enabled = true
    APMEnabled = true

[Metrics]
  Level = "Debug"
  Timeout = "5s"
  Port = 2112
  Path = "/metrics"
  Enabled = false

[Transfers]
  Level = "Debug"

[Governance]
  Level = "Debug"

[Assets]
  Level = "Debug"

[Notary]
  Level = "Debug"

[Subscribers]
  OrderEventLogLevel = "Debug"
  MarketEventLogLevel = "Debug"

[Fee]
  Level = "Debug"

[Broker]
  Level = "Debug"
  [Broker.SocketConfig]
    IP = "0.0.0.0"
    Port = 3005
    MaxReceiveTimeouts = 3
    TransportType = "tcp"

[Nodes]
  Level = "Debug"

[Epochs]
  Level = "Debug"

[Delegations]
  Level = "Debug"

[Checkpoint]
  Level = "Debug"

[NetworkParameters]
  Level = "Debug"

[Pprof]
  Level = "Debug"
  Enabled = false
  Port = 6060
  ProfilesDir = "/tmp"
  BlockProfileRate = 0
  MutexProfileFraction = 0
