# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vega/commands/v1/signature.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n vega/commands/v1/signature.proto\x12\x10vega.commands.v1\"9\n\tSignature\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0c\n\x04\x61lgo\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\rB.Z,code.vegaprotocol.io/protos/vega/commands/v1b\x06proto3')



_SIGNATURE = DESCRIPTOR.message_types_by_name['Signature']
Signature = _reflection.GeneratedProtocolMessageType('Signature', (_message.Message,), {
  'DESCRIPTOR' : _SIGNATURE,
  '__module__' : 'vega.commands.v1.signature_pb2'
  # @@protoc_insertion_point(class_scope:vega.commands.v1.Signature)
  })
_sym_db.RegisterMessage(Signature)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z,code.vegaprotocol.io/protos/vega/commands/v1'
  _SIGNATURE._serialized_start=54
  _SIGNATURE._serialized_end=111
# @@protoc_insertion_point(module_scope)
